name: .NET

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        working-directory: ${{github.workspace}}/CSharp/OrtKISharp
        run: dotnet restore

      - name: Build
        working-directory: ${{github.workspace}}/CSharp/OrtKISharp
        run: dotnet build --no-restore

      - name: Pack
        working-directory: ${{github.workspace}}/CSharp/OrtKISharp
        run: nuget pack

      - name: Upload Package
        working-directory: ${{github.workspace}}/CSharp/OrtKISharp
        run: nuget push *.nupkg 54868e95-5638-4dc7-981d-47fc6d76a7cb -source https://www.myget.org/F/magicallibs/api/v3/index.json
